server:
  address: 0.0.0.0
  port: 8080
  context-path: /
  display-name: CPS Belgium Parts-On-Line

spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://83.166.243.50:5432/CPS
#    username: postgres
#    password: postgres
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/CPS
#    username: postgres
#    password: 14071996
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://ec2-23-21-204-166.compute-1.amazonaws.com:5432/d4ujgq0l4hjfqk?sslmode=require
      username: duafvlefztrjrr
      password: 0f42f58a218c4f57ac73ab5b95bc27a2cd99d7c94afb7f88ea5119a55152b688
  jpa:
      hibernate:
        ddl-auto: update
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  mail:
    host: smtp.gmail.com
    username: testcps24@gmail.com
    password: 123456789aB
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: true
    port: 465
